COLOR_GREEN='\033[1;32m'
echo -e "${COLOR_GREEN}Loading ${HOME}/dotfiles/bash/bashrc ...\033[m"

. ~/dotfiles/bash/env
. ~/dotfiles/bash/config
. ~/dotfiles/bash/aliases
eval "$(/opt/homebrew/bin/brew shellenv)"

# Added by Antigravity
export PATH="/Users/kz/.antigravity/antigravity/bin:$PATH"
